package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"github.com/sipcapture/gossipper/internal/cli"
	"github.com/sipcapture/gossipper/internal/launcher"
	"github.com/sipcapture/gossipper/internal/supervisor"
)

// runWorkerCommand implements `gossipper worker --spec=<file>` — the engine
// process supervised by `gossipper ui`.
//
// The spec carries the job id, data-dir and profile reference. The worker
// resolves the profile to a cli.Config (BuildConfigFromSpec), starts an
// embedded stats streamer on stdout, then hands control to the existing
// launcher.RunSIPScenario so all scenario / engine code is reused.
func runWorkerCommand(args []string) error {
	fs := flag.NewFlagSet("worker", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	specPath := fs.String("spec", "", "path to supervisor worker spec JSON")
	quiet := fs.Bool("quiet", false, "suppress informational stderr output")
	fs.Usage = func() {
		fmt.Fprintf(fs.Output(), `gossipper worker — supervisor-spawned engine worker

The spec JSON file is generated by the master (gossipper ui). It contains the
job id, data-dir, and a profile reference; the worker resolves it to a
cli.Config and launches an engine.

Usage:
  gossipper worker --spec <path>

Flags:
`)
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return err
	}
	if *specPath == "" {
		fs.Usage()
		return errors.New("worker: --spec is required")
	}
	data, err := os.ReadFile(*specPath)
	if err != nil {
		return fmt.Errorf("worker: read spec: %w", err)
	}
	var spec supervisor.Spec
	if err := json.Unmarshal(data, &spec); err != nil {
		return fmt.Errorf("worker: parse spec: %w", err)
	}
	if spec.JobID == "" {
		return errors.New("worker: spec.job_id is required")
	}

	cfg, cleanup, err := supervisor.BuildConfigFromSpec(spec)
	if err != nil {
		emitWorkerEvent("error", map[string]any{"job_id": spec.JobID, "error": err.Error()})
		return err
	}
	defer cleanup()
	cfg.ToolVersion = GetShortVersionString()

	if !*quiet {
		fmt.Fprintf(os.Stderr, "gossipper worker: job_id=%s profile=%s/%s scenario_file=%s\n",
			spec.JobID, spec.ProfileKind, spec.ProfileID, cfg.ScenarioFile)
	}

	baseCtx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	ctx := baseCtx
	if cfg.GlobalTimeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(baseCtx, cfg.GlobalTimeout)
		defer cancel()
	}

	// Stats streamer — best-effort, fully decoupled from the engine.
	interval := time.Duration(spec.StatsIntervalMs) * time.Millisecond
	if interval <= 0 {
		interval = time.Second
	}
	streamCtx, cancelStream := context.WithCancel(ctx)
	var streamWG sync.WaitGroup
	streamWG.Add(1)
	go func() {
		defer streamWG.Done()
		t := time.NewTicker(interval)
		defer t.Stop()
		emitWorkerEvent("started", map[string]any{"job_id": spec.JobID, "pid": os.Getpid()})
		for {
			select {
			case <-streamCtx.Done():
				return
			case <-t.C:
				emitWorkerEvent("stats", map[string]any{
					"job_id": spec.JobID,
					"ts":     time.Now().UTC().Unix(),
				})
			}
		}
	}()

	runErr := launcher.RunSIPScenario(ctx, cfg)
	cancelStream()
	streamWG.Wait()

	if runErr != nil && !errors.Is(runErr, context.Canceled) {
		emitWorkerEvent("exit", map[string]any{"job_id": spec.JobID, "error": runErr.Error()})
		return runErr
	}
	emitWorkerEvent("exit", map[string]any{"job_id": spec.JobID})
	return nil
}

// emitWorkerEvent writes a JSON-lines event to stdout for the master to drain.
func emitWorkerEvent(kind string, payload map[string]any) {
	if payload == nil {
		payload = map[string]any{}
	}
	payload["kind"] = kind
	payload["ts"] = time.Now().UTC().UnixMilli()
	enc, err := json.Marshal(payload)
	if err != nil {
		return
	}
	_, _ = os.Stdout.Write(append(enc, '\n'))
}

// Silence unused-import lints if the file is read in isolation by tooling
// (cli is referenced indirectly through supervisor.BuildConfigFromSpec).
var _ = cli.DefaultTransport
